module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  testMatch: ['**/*.test.{ts,tsx}'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  roots: ['<rootDir>/src'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@components/(.*)$': '<rootDir>/src/component/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@styled/(.*)$': '<rootDir>/src/styled/$1',
    '^@store/(.*)$': '<rootDir>/src/store/$1',
    '^@reducers/(.*)$': '<rootDir>/src/reducers/$1',
    '^@containers/(.*)$': '<rootDir>/src/containers/$1',
    '^@server/(.*)$': '<rootDir>/src/server/$1',
    '^@client/(.*)$': '<rootDir>/src/client/$1',
    '^@css/(.*)$': '<rootDir>/src/css/$1',
    '^@externals/(.*)$': '<rootDir>/src/externals/$1',
    '^@reducers$': '<rootDir>/src/reducers/index',
    '^@store$': '<rootDir>/src/store/index',
    '^@utils$': '<rootDir>/src/utils/index',
    '^@client$': '<rootDir>/src/client/index',
    '^@server$': '<rootDir>/src/server/index',
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
  },
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/server/**',
    '!src/client/**',
    '!src/externals/**',
  ],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
}
